"""Maintains CHANGELOG.json, the patch notes shown on the website's start page and in releases.

    python3 etl/changelog.py add 0.1.2 [--digest NEW --previous-digest OLD]
                                        [--uimap NEW --previous-uimap OLD]
    python3 etl/changelog.py render 0.1.2           # markdown for the GitHub release notes
    python3 etl/changelog.py backfill               # refresh commit lists of released versions
    python3 etl/changelog.py context [--digest …]   # release context for drafting notes (Claude)
    python3 etl/changelog.py merge-notes FILE       # add drafted notes (JSON) to "unreleased"

CHANGELOG.json:
    "unreleased": {"website": [...], "data": [...]}   hand-written notes for the next release
    "versions": [                                      newest first
        {"version", "date",
         "data":        data version (QuestieDB commit, VMangos snapshot),
         "website":     notes on the website (hand-written, from "unreleased"),
         "dataNotes":   notes on the data (hand-written, from "unreleased"),
         "dataChanges": {flavor: [...]} generated by comparing the data with the previous release,
         "commits":     commit subjects (technical details)}
    ]

`add` (run by the release workflow before the image is built) moves the unreleased notes into
the new version, so every image contains its own notes.
"""

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.json"
SKIP_PREFIXES = ("Release v", "Initial commit", "Update data:")
FLAVORS = {"classic": "Classic Era", "forever": "WoW Forever"}
LOCALES = {"enUS": "English", "deDE": "German", "esES": "Spanish (EU)", "esMX": "Spanish (LA)",
           "frFR": "French", "itIT": "Italian", "koKR": "Korean", "ptBR": "Portuguese", "ruRU": "Russian",
           "zhCN": "Chinese (simplified)", "zhTW": "Chinese (traditional)"}
KINDS = {"quest": ("quest", "quests"), "npc": ("NPC", "NPCs"), "object": ("object", "objects"),
         "item": ("item", "items")}
MAX_NAMES = 8


# ---------------------------------------------------------------------------- git

def git(*args):
    return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()


def tags():
    out = git("tag", "-l", "v[0-9]*.[0-9]*.[0-9]*", "--sort=v:refname")
    return [t for t in out.splitlines() if t]


def commits(since, until):
    rng = f"{since}..{until}" if since else until
    lines = git("log", "--reverse", "--format=%s", rng).splitlines()
    return [s for s in lines if s and not s.startswith(SKIP_PREFIXES)]


def data_version(ref):
    try:
        d = json.loads(git("show", f"{ref}:data-version.json"))
    except subprocess.CalledProcessError:
        return None
    return {"questie": {k: d["questie"][k] for k in ("commit", "date", "subject")},
            "vmangos": {k: d["vmangos"][k] for k in ("snapshot", "published")}}


# ---------------------------------------------------------------------------- data changes

def plural(n, kind):
    one, many = KINDS[kind]
    return f"{n:,} {one if n == 1 else many}"


def names(entries, ids):
    shown = sorted((entries[i][0] or f"#{i}" for i in ids), key=str.lower)
    text = ", ".join(shown[:MAX_NAMES])
    return text + (f" and {len(shown) - MAX_NAMES} more" if len(shown) > MAX_NAMES else "")


def describe_flavor(new, old, uimap_new, uimap_old):
    """Plain-language lines describing what changed in one flavor's data."""
    lines = []
    for kind in ("quest", "npc", "object", "item"):
        a, b = old.get(kind, {}), new.get(kind, {})
        added = [i for i in b if i not in a]
        removed = [i for i in a if i not in b]
        updated = [i for i in b if i in a and b[i][1] != a[i][1]]
        if kind == "quest":
            if added:
                lines.append(f"{plural(len(added), kind)} added: {names(b, added)}.")
            if removed:
                lines.append(f"{plural(len(removed), kind)} removed: {names(a, removed)}.")
            if updated:
                lines.append(f"{plural(len(updated), kind)} updated (texts, objectives, rewards or chains), "
                             f"e.g. {names(b, updated[:MAX_NAMES])}.")
        else:
            parts = [f"{len(added):,} added" if added else "", f"{len(removed):,} removed" if removed else "",
                     f"{len(updated):,} updated" if updated else ""]
            parts = [p for p in parts if p]
            if parts:
                lines.append(f"{KINDS[kind][1]}: {', '.join(parts)}.")

    text_changes = []
    for locale, label in LOCALES.items():
        before = old.get("texts", {}).get(locale, {}).get("details", 0)
        after = new.get("texts", {}).get(locale, {}).get("details", 0)
        if after != before:
            text_changes.append(f"{label} {after - before:+,}")
    if text_changes:
        lines.append("Quest descriptions: " + ", ".join(text_changes) + ".")

    if new.get("questlines") != old.get("questlines") and old.get("questlines") is not None:
        diff = new["questlines"] - old["questlines"]
        lines.append(f"Questlines: {new['questlines']:,} ({diff:+,}).")

    if uimap_new is not None and uimap_old is not None:
        have = lambda r: sum(1 for _, ui in r["quests"].values() if ui)
        diff = have(uimap_new) - have(uimap_old)
        if diff:
            lines.append(f"Map IDs (uiMapId): {have(uimap_new):,} quests with a map ({diff:+,}).")
    return lines or ["No changes to quests, NPCs, objects or items."]


def data_changes(digest, previous, uimap, previous_uimap):
    if not digest or not previous:
        return None
    out = {}
    for flavor, label in FLAVORS.items():
        if flavor in digest:
            out[flavor] = describe_flavor(digest[flavor], previous.get(flavor, {}),
                                          (uimap or {}).get(flavor), (previous_uimap or {}).get(flavor))
    return out


# ---------------------------------------------------------------------------- file

def load():
    if CHANGELOG.exists():
        log = json.loads(CHANGELOG.read_text(encoding="utf-8"))
    else:
        log = {}
    log.setdefault("_comment", "Patch notes for the website and releases. Maintained by etl/changelog.py; "
                               "add notes for the next release under 'unreleased'.")
    log.setdefault("unreleased", {"website": [], "data": []})
    log.setdefault("versions", [])
    return log


def save(log):
    log["versions"].sort(key=lambda e: [int(x) for x in e["version"].split(".")], reverse=True)
    CHANGELOG.write_text(json.dumps(log, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def read_json(path):
    """JSON or gzipped JSON (*.gz); None if the path is empty or missing."""
    if not path or not Path(path).exists():
        return None
    if str(path).endswith(".gz"):
        import gzip
        with gzip.open(path, "rt", encoding="utf-8") as f:
            return json.load(f)
    return json.loads(Path(path).read_text())


def render(entry):
    """Markdown for the GitHub release notes."""
    md = []
    if entry.get("website"):
        md += ["## Website", ""] + [f"- {n}" for n in entry["website"]] + [""]
    if entry.get("dataNotes") or entry.get("dataChanges"):
        md += ["## Data", ""]
        md += [f"- {n}" for n in entry.get("dataNotes", [])]
        for flavor, lines in (entry.get("dataChanges") or {}).items():
            md += [f"- **{FLAVORS.get(flavor, flavor)}:** " + " ".join(lines)]
        md.append("")
    if entry.get("commits"):
        md += ["<details><summary>Technical changes</summary>", ""] + [f"- {c}" for c in entry["commits"]]
        md += ["", "</details>", ""]
    return "\n".join(md)


# ---------------------------------------------------------------------------- drafting with Claude

def context(args):
    """Markdown describing everything since the last release, for drafting patch notes."""
    existing = tags()
    last = existing[-1] if existing else None
    rng = f"{last}..HEAD" if last else "HEAD"
    log = load()
    out = [f"# Changes since {last or 'the beginning'}", ""]
    out += ["## Commits (subject and description)", ""]
    raw = git("log", "--reverse", "--format=%x1e%s%x1f%b", rng)
    for record in filter(None, raw.split("\x1e")):
        subject, _, body = record.partition("\x1f")
        if subject.startswith(SKIP_PREFIXES):
            continue
        body = "\n".join(l for l in body.strip().splitlines() if not l.startswith(("Co-Authored-By", "Claude-Session")))
        out += [f"### {subject}", "", body.strip(), ""]
    files = git("diff", "--stat=200", rng, "--", ".", ":(exclude)vendor", ":(exclude)CHANGELOG.json") if last else ""
    if files:
        out += ["## Changed files", "", "```", files, "```", ""]
    changes = data_changes(read_json(args.digest), read_json(args.previous_digest),
                           read_json(args.uimap), read_json(args.previous_uimap))
    out += ["## Data changes (computed, will be shown automatically)", ""]
    if changes:
        for flavor, lines in changes.items():
            out.append(f"- {FLAVORS.get(flavor, flavor)}: " + " ".join(lines))
    else:
        out.append("- (no comparison available)")
    out += ["", "## Notes already written (keep them, do not repeat them)", ""]
    for key in ("website", "data"):
        for note in log["unreleased"].get(key, []):
            out.append(f"- [{key}] {note}")
    if not any(log["unreleased"].get(k) for k in ("website", "data")):
        out.append("- (none)")
    return "\n".join(out)


def merge_notes(path):
    """Adds drafted notes to "unreleased"; accepts the JSON object anywhere in the text."""
    text = Path(path).read_text(encoding="utf-8")
    start, end = text.find("{"), text.rfind("}")
    if start < 0 or end <= start:
        sys.exit("no JSON object in the drafted notes")
    drafted = json.loads(text[start:end + 1])
    log = load()
    added = 0
    for key in ("website", "data"):
        notes = drafted.get(key, [])
        if not isinstance(notes, list) or not all(isinstance(n, str) for n in notes):
            sys.exit(f"'{key}' must be a list of strings")
        current = log["unreleased"].setdefault(key, [])
        known = {n.strip().lower() for n in current}
        for note in notes:
            note = " ".join(note.split())
            if note and note.lower() not in known and len(note) <= 400:
                current.append(note)
                known.add(note.lower())
                added += 1
    save(log)
    print(f"added {added} drafted notes", file=sys.stderr)


# ---------------------------------------------------------------------------- commands

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    add = sub.add_parser("add")
    add.add_argument("version")
    add.add_argument("--digest")
    add.add_argument("--previous-digest")
    add.add_argument("--uimap")
    add.add_argument("--previous-uimap")
    rend = sub.add_parser("render")
    rend.add_argument("version")
    sub.add_parser("backfill")
    ctx = sub.add_parser("context")
    for flag in ("--digest", "--previous-digest", "--uimap", "--previous-uimap"):
        ctx.add_argument(flag)
    merge = sub.add_parser("merge-notes")
    merge.add_argument("file")
    args = ap.parse_args()
    if args.cmd == "context":
        print(context(args))
        return
    if args.cmd == "merge-notes":
        merge_notes(args.file)
        return
    log = load()

    if args.cmd == "render":
        entry = next((e for e in log["versions"] if e["version"] == args.version.lstrip("v")), None)
        if entry is None:
            sys.exit(f"version {args.version} not in CHANGELOG.json")
        print(render(entry))
        return

    if args.cmd == "backfill":
        previous = None
        for tag in tags():
            entry = next((e for e in log["versions"] if e["version"] == tag[1:]), None)
            if entry is None:
                entry = {"version": tag[1:], "website": [], "dataNotes": []}
                log["versions"].append(entry)
            entry["date"] = git("log", "-1", "--format=%cs", tag)
            entry["commits"] = commits(previous, tag)
            entry["data"] = data_version(tag) or entry.get("data")
            previous = tag
    else:
        version = args.version.lstrip("v")
        existing = tags()
        unreleased = log["unreleased"]
        entry = {
            "version": version,
            "date": date.today().isoformat(),
            "data": data_version("HEAD"),
            "website": unreleased.get("website", []),
            "dataNotes": unreleased.get("data", []),
            "dataChanges": data_changes(read_json(args.digest), read_json(args.previous_digest),
                                        read_json(args.uimap), read_json(args.previous_uimap)),
            "commits": commits(existing[-1] if existing else None, "HEAD"),
        }
        log["versions"] = [e for e in log["versions"] if e["version"] != version] + [
            {k: v for k, v in entry.items() if v is not None}]
        log["unreleased"] = {"website": [], "data": []}
    save(log)
    for e in log["versions"]:
        print(f"{e['version']} ({e.get('date')}): {len(e.get('website', []))} website notes, "
              f"{len(e.get('dataNotes', []))} data notes, {len(e.get('commits', []))} commits")


if __name__ == "__main__":
    main()
